Controllers films users
fernandocortez8547/java-filmorate pull request #4
Opened 2023-02-27 09:03 UTC by fernandocortez8547

Сделал откат main, отправляю пул реквест

2023-02-27 21:11 UTC, alexache requested changes

2023-03-02 20:37 UTC, fernandocortez8547 commented
-добавил в проект spring-boot-starter-validation.
-пришлось организовать валидацию в классе менеджеров всё равно в ручную. С помощью аннотаций @Validated и @Validate работало только в контроллере, а это как минимум мешает провести тесты. Не смог понять как это исправить иначе.
-сообщение для ValidationExeption теперь берется из списка ConstraintViolation, так кажется информативнее.

2023-03-03 18:10 UTC, alexache approved these changes

2023-03-03 18:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/manager/InMemoryUserManager.java
> +        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
Комментарии прочел, но выглядит все равно сложнее, чем можно было бы сделать. @Validated/@Valid правильный путь. Тесты немного второстепенны, не стоит реализацию менять только из-за тестов. Как раз для тестов можно создавать валидатор вручную, как ты делаешь через validator.validate

2023-03-06 20:04 UTC, merged