Add friends, likes
fernandocortez8547/java-filmorate pull request #5
Opened 2023-03-12 22:50 UTC by fernandocortez8547

Помимо тз переделал прошлые замечания по поводу валидаций.

2023-03-13 23:25 UTC, alexache requested changes

2023-03-13 23:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +		InMemoryFilmStorage filmStorage = context.getBean(InMemoryFilmStorage.class);
Для чего эти строки получения бинов?

2023-03-13 23:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(InMemoryFilmStorage filmStorage, InMemoryUserStorage userStorage) {
- Не должно быть явного обращения к конкретным реалзациями, тут должны указывать интерфейсы стораджей:
- Для чего вообще вручную создавать сервис? Нужно указать спрингу, что он нужен, а спринг должен сам создать объект

2023-03-13 23:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getMostPopularFilms(@RequestParam(defaultValue = "11") int count) {
А разве не 10 должно быть по умолчанию?

2023-03-13 23:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService = new UserService(userStorage);
Такой же комментарий, как и в контроллере фильмов

2023-03-13 23:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
Не помешает такие поля пометить как @JsonIgnore, так как их необязательно возвращать из контроллера

2023-03-13 23:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
@Autowired?

2023-03-14 19:20 UTC, fernandocortez8547 commented
Здравствуйте, кажется исправил всё, кроме @JsonIgnore. Такая версия не проходит тесты гитхаба с постманом. В тестах видимо сравнение с присутствием переменной 'name'. Не оч гибкая аннотация по настройке, либо я не понял как присвоить полю значение логин по дефолту. 
Хотел спросить тут, корректно ли присылать ссылку на эту страницу пул реквеста при повторной проверке /java-filmorate/pull/5 ? ту же самую ссылку по сути

2023-03-15 14:02 UTC, alexache approved these changes

2023-03-15 14:02 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/InMemoryUserManagerTest.java
> +//
(опционально) Закомментированный код, по традиции, лучше удалять :)

2023-03-19 19:42 UTC, merged